services:
  postgres:
    image: postgres:18.4
    container_name: db
    env_file:
      - ../.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

  app:
    container_name: app
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - ../.:/app
      - /app/node_modules
    command: npm run start:dev

  maildev:
    container_name: maildev
    image: maildev/maildev:latest
    ports:
      - '1080:1080'
      - '1025:1025'
    environment:
      - MAILDEV_MAIL_DIRECTORY=/data/mail
    user: root
    volumes:
      - maildev_data:/home/maildev/data

volumes:
  postgres_data:
  maildev_data:
    driver: local
